### PR TITLE
Added .gitignore to avoid accidentally committing files that shouldn't be committed.

### PR DESCRIPTION
**Pull request by ak9999**

### CODE REVIEW

**Comment by mgarod** [comment]
I'll be honest, not sure what a .gitignore does, or if this is a good idea to merge.

**Comment by ak9999** [comment]
Each line in a .gitignore file is a pattern. So any file names or file paths matching the patterns will be purposely ignored. This is to avoid accidentally uploading *.xml and *.iml files that IDEs like IntelliJ IDEA will create when we work, and we can also ignore directories that get created when building the application. It is just to keep the repo neat.

**Comment by mgarod** [comment]
Alright I guess.

**Comment by mgarod** [comment]
Whoops That's not what I wanted to do.

**Pull request merged**
